version: '3.8'

services:
  soroka-bot:
    image: gihar/soroka:latest  # Замените на ваш username
    container_name: soroka-bot
    restart: unless-stopped
    environment:
      # Основные настройки
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SSL_VERIFY=${SSL_VERIFY:-false}
      
      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      
      # Anthropic
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      
      # Yandex GPT
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
      
      # База данных
      - DATABASE_URL=${DATABASE_URL:-sqlite:///bot.db}
      
      # Настройки файлов
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-20971520}
      - MAX_EXTERNAL_FILE_SIZE=${MAX_EXTERNAL_FILE_SIZE:-52428800}
      - TEMP_DIR=${TEMP_DIR:-temp}
      
      # Транскрипция
      - TRANSCRIPTION_MODE=${TRANSCRIPTION_MODE:-hybrid}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-whisper-large-v3-turbo}
      
      # Диаризация
      - ENABLE_DIARIZATION=${ENABLE_DIARIZATION:-false}
      - DIARIZATION_PROVIDER=${DIARIZATION_PROVIDER:-whisperx}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - PICOVOICE_ACCESS_KEY=${PICOVOICE_ACCESS_KEY}
      - DIARIZATION_DEVICE=${DIARIZATION_DEVICE:-auto}
      - COMPUTE_TYPE=${COMPUTE_TYPE:-auto}
      - MAX_SPEAKERS=${MAX_SPEAKERS:-10}
      - MIN_SPEAKERS=${MIN_SPEAKERS:-1}
    
    volumes:
      # Монтируем директории для персистентности данных
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./cache:/app/cache
      - ./bot.db:/app/bot.db
    
    ports:
      - "8080:8080"  # Для веб-хуков (если понадобится)
    
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
